-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: HitCounters2/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE hitcounters2_hitcounter (
  pageid BIGINT NOT NULL,
  hits BIGINT NOT NULL,
  PRIMARY KEY(pageid)
);

CREATE INDEX pageid ON hitcounters2_hitcounter (pageid);