-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: HitCounters2/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/hitcounters2_hitcounter (
  pageid BIGINT UNSIGNED NOT NULL,
  hits BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY(pageid)
);

CREATE INDEX pageid ON /*_*/hitcounters2_hitcounter (pageid);